# TODO(jlewi): This kustomization.yaml is deprecated. We want the
# base_v3 version. This version uses a bunch of problematic patterns e.g.
# i) Using vars to do command line substitution
# ii) Not using a configmap to make application and global config available
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
patchesStrategicMerge:
- patches/manager.yaml

images:
- name: docker.io/kubeflownotebookswg/profile-controller
  newName: docker.io/kubeflownotebookswg/profile-controller
<<<<<<< HEAD
  newTag: v1.7.0
=======
  newTag: v1.9.0
>>>>>>> 48b8643bee14b8c85c3de9f6d129752bb55b44d3

configMapGenerator:
- name: namespace-labels-data
  files:
  - namespace-labels.yaml
