apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
configMapGenerator:
- name: tensorboard-controller-config
  literals:
  - RWO_PVC_SCHEDULING="True"
  - TENSORBOARD_IMAGE=tensorflow/tensorflow:2.5.1
  - ISTIO_GATEWAY=kubeflow/kubeflow-gateway
  - ISTIO_HOST=*
patchesStrategicMerge:
- patches/add_controller_config.yaml
images:
- name: docker.io/kubeflownotebookswg/tensorboard-controller
  newName: docker.io/kubeflownotebookswg/tensorboard-controller
<<<<<<< HEAD
  newTag: v1.7.0
=======
  newTag: v1.9.0
>>>>>>> 48b8643bee14b8c85c3de9f6d129752bb55b44d3
